packages:
  - .
  - pkgs/*
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.6.1+sha512-lPSj+EssR8xMZTnhD2NIViGoFw3X4xilYSZ5uDC3AtVaEmyqfc9kYhKyYGnyKYm5bHQ58WyZxcpUevuOmMMkIQ==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
preferFrozenLockfile: true
