packages:
  - .
  - pkgs/*
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.4.2+sha512-psEBPeRC6fDGpnwSiRrYPqWi9yvHudqkbXdEIxrwbxhHBiOKiflCYZdkIs57fyzg5GRyFLXtwhZ/D4viiEm/vQ==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
preferFrozenLockfile: true
