packages:
  - .
  - pkgs/*
catalog:
  "@savvy-web/changesets": ^0.1.2
  "@savvy-web/commitlint": ^0.3.4
  "@savvy-web/lint-staged": ^0.4.6
  "@savvy-web/vitest": ^0.1.0
catalogMode: strict
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.7.0+sha512-ZkdJQlf2q87o36FnegjeFpbQ2M52UnIuniq4DkUsYFxCrDEvXGAX8MhxzOOt9mBtQFmRXoKLoSmJb9I2NxVjIg==
loglevel: info
